import CoreGraphics
import Foundation

/// Compose one mark and one plate into a **vector** app icon.
///
/// The third output of `icon build`, beside the `.appiconset` and the `.icon`, and the
/// one that is not for Xcode. A marketing site needs the same icon as a favicon, an
/// `apple-touch-icon`, an OG card and usually a press-kit download, and every one of
/// those wants the plated artwork rather than the bare mark. Rasterising them from a
/// 1024 PNG loses the two that should stay vector, so the site ends up with a
/// hand-written SVG transcribing the same geometry — which drifts from the app's icon
/// the first time either moves.
///
/// So this emits the plated icon as SVG, from the same mark, the same plate and the same
/// placement arithmetic as the raster formats. One `icon build` per output, one geometry
/// behind all of them.
///
/// ## This one keeps its corner radius
///
/// The opposite of the `.icon` rule, for the opposite reason. A `.icon` layer is square
/// because the system masks it; nothing masks an SVG on a web page, so it carries its own
/// rounded plate or it renders as a hard square. `defaultCornerRadius` is Apple's own
/// proportion carried onto a full-bleed canvas — the pre-Tahoe grid's 185pt radius on its
/// 824pt plate, scaled to 1024.
///
/// Pass `cornerRadius: 0` for the square plate an `apple-touch-icon` wants, since iOS
/// masks that one itself and a rounded source gets rounded twice, leaving a sliver at
/// each corner.
public enum IconSVG {
    /// Apple's 185-on-824 corner radius, rescaled to a full-bleed 1024 canvas.
    public static let defaultCornerRadius = 1024.0 * 185.0 / 824.0

    /// The gradient's id. Distinctive because ids are document-global in SVG and this
    /// document also contains whatever the mark brought with it.
    static let gradientID = "appshot-plate"

    /// Compose `mark` on a plate and return the SVG source.
    ///
    /// The mark must itself be SVG. PDF and bitmap marks work for the raster formats,
    /// which rasterise everything anyway, but there is no honest way to put them in a
    /// vector document — embedding a PNG in an SVG produces a file that is vector only
    /// in its file extension.
    public static func compose(
        mark: URL,
        pixels: Int = IconComposer.layerPixels,
        options: Icon.Options = Icon.Options(),
        cornerRadius: Double = defaultCornerRadius,
        label: String? = nil
    ) throws -> String {
        guard mark.pathExtension.lowercased() == "svg" else {
            throw AppShotError.svgOutputNeedsSVGMark(mark)
        }
        let parsed = try Mark(contentsOf: mark)
        let canvas = Double(pixels)

        // Identical placement to the raster path, from the same function, because an SVG
        // favicon sitting a few pixels off from the app icon is exactly the drift this
        // output exists to remove.
        let box = IconComposer.markBox(pixels: pixels, markFraction: options.markFraction)
        let scale = min(box.width / parsed.width, box.height / parsed.height)
        let drawnW = parsed.width * scale
        let drawnH = parsed.height * scale
        // The box is centred on a square canvas, so y-up and y-down agree on these.
        let tx = box.midX - drawnW / 2 - parsed.minX * scale
        let ty = box.midY - drawnH / 2 - parsed.minY * scale

        var out: [String] = []
        out.append(
            """
            <svg xmlns="http://www.w3.org/2000/svg" width="\(n(canvas))" height="\(n(canvas))"
                 viewBox="0 0 \(n(canvas)) \(n(canvas))"\(label.map { " role=\"img\" aria-label=\"\(escape($0))\"" } ?? "")>
            """)
        out.append("  <!-- GENERATED by appshot icon build — do not edit. -->")

        // One <defs> for both, because a document may need the gradient and the effects and
        // two <defs> blocks is the kind of thing that renders fine and reviews badly.
        var defs: [String] = []
        if case .gradient(let background) = options.plate {
            let (start, end) = Compose.gradientAxis(background, width: canvas, height: canvas)
            defs.append(
                "    <linearGradient id=\"\(gradientID)\" gradientUnits=\"userSpaceOnUse\""
                    + " x1=\"\(n(start.x))\" y1=\"\(n(start.y))\""
                    + " x2=\"\(n(end.x))\" y2=\"\(n(end.y))\">")
            for stop in background.stops {
                defs.append(
                    "      <stop offset=\"\(n(stop.offset))\" stop-color=\"\(stop.color)\"/>")
            }
            defs.append("    </linearGradient>")
        }
        if !options.effects.isEmpty {
            // Effects are authored in canvas units on a 1024 canvas; this document may be
            // any size, and the filter is applied outside the mark's own transform, so the
            // only conversion needed is canvas-to-canvas.
            defs += IconEffect.svgFilter(options.effects, scale: canvas / Icon.canvas)
        }
        if !defs.isEmpty {
            out.append("  <defs>")
            out += defs
            out.append("  </defs>")
        }

        switch options.plate {
        case .gradient:
            out.append(plateRect(canvas: canvas, radius: cornerRadius, fill: "url(#\(gradientID))"))
        case .solid(let hex):
            out.append(plateRect(canvas: canvas, radius: cornerRadius, fill: hex))
        case .none:
            break
        }

        // `fill` and `color` together: `color` is what a mark authored with
        // `currentColor` reads, `fill` covers one that simply inherits. A mark with its
        // own baked fills keeps them, which is the same artwork the untinted raster path
        // would draw — `--tint` is documented for currentColor marks, and this is the
        // vector reading of it.
        let tintAttrs = options.tint.map { " fill=\"\($0)\" color=\"\($0)\"" } ?? ""
        // The filter goes on an outer group, outside the mark's own transform. Inside it,
        // the filter's lengths would be in the mark's coordinate system — which is whatever
        // viewBox the artwork happened to be drawn in — and the same offset would mean a
        // different distance for every mark.
        let filtered = !options.effects.isEmpty
        if filtered {
            out.append("  <g filter=\"url(#\(IconEffect.filterID))\">")
        }
        out.append(
            "  <g transform=\"translate(\(n(tx)) \(n(ty))) scale(\(n(scale)))\""
                + "\(parsed.inheritedAttributes)\(tintAttrs)>")
        out.append(parsed.body)
        out.append("  </g>")
        if filtered {
            out.append("  </g>")
        }
        out.append("</svg>")
        return out.joined(separator: "\n") + "\n"
    }

    static func plateRect(canvas: Double, radius: Double, fill: String) -> String {
        let rx = radius > 0 ? " rx=\"\(n(radius))\"" : ""
        return "  <rect x=\"0\" y=\"0\" width=\"\(n(canvas))\" height=\"\(n(canvas))\""
            + "\(rx) fill=\"\(fill)\"/>"
    }

    // MARK: - Reading the mark

    /// The mark's intrinsic box and its drawable content.
    struct Mark {
        let minX: Double
        let minY: Double
        let width: Double
        let height: Double
        /// Everything inside the mark's root `<svg>`, verbatim — `defs`, `style`, groups
        /// and all. Kept as source rather than re-serialised shapes so a mark using
        /// gradients, masks or a stylesheet survives the trip.
        let body: String
        /// Root attributes that affect how the body renders and would be lost with the
        /// root element itself.
        let inheritedAttributes: String

        init(contentsOf url: URL) throws {
            guard let doc = try? XMLDocument(contentsOf: url, options: [.nodePreserveWhitespace]),
                let root = doc.rootElement()
            else {
                throw AppShotError.imageDecodeFailed(url)
            }

            // viewBox wins: it is the coordinate system the body is drawn in, whereas
            // width/height may be a display size in any unit.
            if let viewBox = root.attribute(forName: "viewBox")?.stringValue {
                let parts =
                    viewBox
                    .split(whereSeparator: { $0 == " " || $0 == "," })
                    .compactMap { Double($0) }
                guard parts.count == 4, parts[2] > 0, parts[3] > 0 else {
                    throw AppShotError.imageDecodeFailed(url)
                }
                (minX, minY, width, height) = (parts[0], parts[1], parts[2], parts[3])
            } else {
                let w = Self.length(root.attribute(forName: "width")?.stringValue)
                let h = Self.length(root.attribute(forName: "height")?.stringValue)
                guard let w, let h, w > 0, h > 0 else {
                    throw AppShotError.imageDecodeFailed(url)
                }
                (minX, minY, width, height) = (0, 0, w, h)
            }

            body = (root.children ?? [])
                .map { $0.xmlString }
                .joined(separator: "\n")

            let carried = ["fill", "stroke", "stroke-width", "color", "style", "opacity"]
            inheritedAttributes = carried.compactMap { name in
                root.attribute(forName: name)?.stringValue.map { " \(name)=\"\($0)\"" }
            }.joined()
        }

        /// Strip a unit suffix — `px`, `pt` and friends all resolve to user units here,
        /// which is right for the only case this path serves: a mark with no viewBox,
        /// whose width and height *are* its coordinate system.
        static func length(_ value: String?) -> Double? {
            guard let value else { return nil }
            let digits = value.prefix { $0.isNumber || $0 == "." || $0 == "-" || $0 == "+" }
            return Double(digits)
        }
    }

    // MARK: - Formatting

    /// Trim trailing zeros so the output diffs cleanly between runs and between projects.
    static func n(_ value: Double) -> String {
        if value == value.rounded(), abs(value) < 1e15 {
            return String(Int(value.rounded()))
        }
        return String(format: "%.4f", value)
            .replacingOccurrences(of: "0+$", with: "", options: .regularExpression)
            .replacingOccurrences(of: "\\.$", with: "", options: .regularExpression)
    }

    static func escape(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
